### PR TITLE
Some solution using maxflow

### LINKED ISSUE #3: Some

### PR DESCRIPTION
**Pull request by ChrBank**
Fix #3

### CODE REVIEW

**Review by lucasfth — CHANGES_REQUESTED** [review]
It should just replace my some solution as it is very slow

**Comment by A-Guldborg** [comment]
> It should just replace my some solution as it is very slow

Done, please re-review

**Review by lucasfth — APPROVED** [review]
I have no idea what is going on. I guess it is fine

**Comment by lucasfth** [comment]
Fix #3

**Comment by A-Guldborg** [comment]
Anyone else has an opinion before merging? 👀

**Pull request merged**
